# Generated by Django 5.2 on 2025-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="student",
            name="batch",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="student",
            name="floor",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
