# Generated by Django 5.2 on 2025-05-04 15:37

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyMealCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name="monthlymealsummary",
            name="actual_meal_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="monthlymealsummary",
            name="days_meal_consumed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthlymealsummary",
            name="meal_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.mealtype",
            ),
        ),
        migrations.AddField(
            model_name="monthlymealsummary",
            name="total_meal_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="monthlymealsummary",
            name="month",
            field=models.DateField(default=students.models.first_day_of_current_month),
        ),
        migrations.AlterField(
            model_name="monthlymealtype",
            name="month",
            field=models.DateField(default=students.models.first_day_of_current_month),
        ),
    ]
