# Generated by Django 5.2 on 2025-05-09 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0002_weeklymealcost_monthlymealsummary_actual_meal_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymealstatus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailymealstatus",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
