# Generated by Django 5.2 on 2025-05-09 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_dailymealstatus_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlymealsummary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlymealsummary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="monthlymealtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlymealtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
