# Generated by Django 5.2 on 2025-05-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_email_alter_student_phone_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MealSummary",
            new_name="MonthlyMealSummary",
        ),
    ]
