# Generated by Django 5.2 on 2025-05-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_rename_mealsummary_monthlymealsummary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlymealsummary",
            old_name="only_meal_cost",
            new_name="actual_meal_cost",
        ),
        migrations.RemoveField(
            model_name="monthlymealsummary",
            name="total_meal_cost",
        ),
        migrations.RemoveField(
            model_name="student",
            name="ongoing_meal_cost",
        ),
        migrations.RemoveField(
            model_name="student",
            name="total_meal_cost",
        ),
    ]
