# Generated by Django 5.2 on 2025-05-09 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_monthlymealsummary_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealtype",
            name="cost_per_day",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
