# Generated by Django 5.2 on 2025-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0005_rename_only_meal_cost_monthlymealsummary_actual_meal_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailymealstatus",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
