# Generated by Django 5.2 on 2025-05-09 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_mealtype_cost_per_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklymealcost",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddIndex(
            model_name="dailymealstatus",
            index=models.Index(
                fields=["student", "date"], name="students_da_student_1bb348_idx"
            ),
        ),
    ]
