# Generated by Django 5.2 on 2025-05-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_alter_dailymealstatus_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlymealtype",
            name="meal_type",
            field=models.IntegerField(choices=[(1, "Beef"), (2, "Fish")]),
        ),
    ]
